name: Build and Sign

on:
  push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore ./src/Tableau.Migration.App.GUI

      - name: Build
        run: dotnet build  ./src/Tableau.Migration.App.GUI --configuration Release --no-restore

      - name: Create Releases for Winx64, OSX-x64, OSX-arm64, Linux-x64, Linux-arm64
        run: |
          ./scripts/release.ps1

      - name: Package up OSX files into .app format
        run: |
          ./scripts/macos.sh --x64 &&
          ./scripts/macos.sh --arm64

      - name: Sign Windows App
        env:
          ARTIFACTORY_APIKEY: ${{ secrets.ARTIFACTORY_APIKEY }}
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          GITLAB_APIKEY: ${{ secrets.GITLAB_APIKEY }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          TEAMCITY_APIKEY: ${{ secrets.TEAMCITY_APIKEY }}
        run: pwsh ./scripts/SignWindowsExecutable.ps1
      
      - name: Create ZIP files
        run: |
          Compress-Archive -Path ./build/win_x64/* -DestinationPath TableauMigrationApp_win-x64.zip &&
          Compress-Archive -Path ./build/osx_arm64_macapp/ -DestinationPath TableauMigrationApp_osx-arm64.zip &&
          Compress-Archive -Path ./build/osx_x64_macapp/ -DestinationPath TableauMigrationApp_osx-x64.zip &&
          Compress-Archive -Path./build/linux_arm64/* -DestinationPath TableauMigrationApp_linux-arm64.zip &&
          Compress-Archive -Path ./build/linux_x64/* -DestinationPath TableauMigrationApp_linux-x64.zip
      
      