name: Build and Release

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore ./src/MigrationApp.GUI

    - name: Build
      run: dotnet build  ./src/MigrationApp.GUI --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./src/MigrationApp.GUI --configuration Release --self-contained --runtime win-x64 /p:PublishSingleFile=true /p:DebugType=None -o ./build

    - name: Create ZIP file
      run: zip -j TableauMigrationApp.zip ./build/*

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./TableauMigrationApp.zip
        asset_name: TableauMigrationApp.zip
        asset_content_type: application/zip
